module Yoomoney
  module Models
    type airline =
      {
        booking_reference: String,
        legs: ::Array[Yoomoney::AirlineLeg],
        passengers: ::Array[Yoomoney::AirlinePassenger],
        ticket_number: String
      }

    class Airline < Yoomoney::Internal::Type::BaseModel
      attr_reader booking_reference: String?

      def booking_reference=: (String) -> String

      attr_reader legs: ::Array[Yoomoney::AirlineLeg]?

      def legs=: (
        ::Array[Yoomoney::AirlineLeg]
      ) -> ::Array[Yoomoney::AirlineLeg]

      attr_reader passengers: ::Array[Yoomoney::AirlinePassenger]?

      def passengers=: (
        ::Array[Yoomoney::AirlinePassenger]
      ) -> ::Array[Yoomoney::AirlinePassenger]

      attr_reader ticket_number: String?

      def ticket_number=: (String) -> String

      def initialize: (
        ?booking_reference: String,
        ?legs: ::Array[Yoomoney::AirlineLeg],
        ?passengers: ::Array[Yoomoney::AirlinePassenger],
        ?ticket_number: String
      ) -> void

      def to_hash: -> {
        booking_reference: String,
        legs: ::Array[Yoomoney::AirlineLeg],
        passengers: ::Array[Yoomoney::AirlinePassenger],
        ticket_number: String
      }
    end
  end
end
