module Yoomoney
  module Models
    type airline =
      {
        booking_reference: String,
        legs: ::Array[Yoomoney::Airline::Leg],
        passengers: ::Array[Yoomoney::Airline::Passenger],
        ticket_number: String
      }

    class Airline < Yoomoney::Internal::Type::BaseModel
      attr_reader booking_reference: String?

      def booking_reference=: (String) -> String

      attr_reader legs: ::Array[Yoomoney::Airline::Leg]?

      def legs=: (
        ::Array[Yoomoney::Airline::Leg]
      ) -> ::Array[Yoomoney::Airline::Leg]

      attr_reader passengers: ::Array[Yoomoney::Airline::Passenger]?

      def passengers=: (
        ::Array[Yoomoney::Airline::Passenger]
      ) -> ::Array[Yoomoney::Airline::Passenger]

      attr_reader ticket_number: String?

      def ticket_number=: (String) -> String

      def initialize: (
        ?booking_reference: String,
        ?legs: ::Array[Yoomoney::Airline::Leg],
        ?passengers: ::Array[Yoomoney::Airline::Passenger],
        ?ticket_number: String
      ) -> void

      def to_hash: -> {
        booking_reference: String,
        legs: ::Array[Yoomoney::Airline::Leg],
        passengers: ::Array[Yoomoney::Airline::Passenger],
        ticket_number: String
      }

      type leg =
        {
          departure_airport: String,
          departure_date: String,
          destination_airport: String,
          carrier_code: String
        }

      class Leg < Yoomoney::Internal::Type::BaseModel
        attr_accessor departure_airport: String

        attr_accessor departure_date: String

        attr_accessor destination_airport: String

        attr_reader carrier_code: String?

        def carrier_code=: (String) -> String

        def initialize: (
          departure_airport: String,
          departure_date: String,
          destination_airport: String,
          ?carrier_code: String
        ) -> void

        def to_hash: -> {
          departure_airport: String,
          departure_date: String,
          destination_airport: String,
          carrier_code: String
        }
      end

      type passenger = { first_name: String, last_name: String }

      class Passenger < Yoomoney::Internal::Type::BaseModel
        attr_accessor first_name: String

        attr_accessor last_name: String

        def initialize: (first_name: String, last_name: String) -> void

        def to_hash: -> { first_name: String, last_name: String }
      end
    end
  end
end
