module Yoomoney
  module Models
    type b2b_sberbank_calculated_vat_data =
      { amount: Yoomoney::MonetaryAmount, rate: String }

    class B2bSberbankCalculatedVatData < Yoomoney::Models::B2bSberbankVatData
      def amount: -> Yoomoney::MonetaryAmount

      def amount=: (Yoomoney::MonetaryAmount _) -> Yoomoney::MonetaryAmount

      def rate: -> String

      def rate=: (String _) -> String

      def initialize: (amount: Yoomoney::MonetaryAmount, rate: String) -> void

      def to_hash: -> { amount: Yoomoney::MonetaryAmount, rate: String }
    end
  end
end
