module Yoomoney
  module Models
    type b2b_sberbank_vat_data =
      { type: Yoomoney::Models::B2bSberbankVatData::type_ }

    class B2bSberbankVatData < Yoomoney::Internal::Type::BaseModel
      attr_accessor type: Yoomoney::Models::B2bSberbankVatData::type_

      def initialize: (
        type: Yoomoney::Models::B2bSberbankVatData::type_
      ) -> void

      def to_hash: -> { type: Yoomoney::Models::B2bSberbankVatData::type_ }

      type type_ = :calculated | :untaxed | :mixed

      module Type
        extend Yoomoney::Internal::Type::Enum

        CALCULATED: :calculated
        UNTAXED: :untaxed
        MIXED: :mixed

        def self?.values: -> ::Array[Yoomoney::Models::B2bSberbankVatData::type_]
      end
    end
  end
end
