module Yoomoney
  module Models
    type deal_retrieve_params =
      { deal_id: String } & Yoomoney::Internal::Type::request_parameters

    class DealRetrieveParams < Yoomoney::Internal::Type::BaseModel
      extend Yoomoney::Internal::Type::RequestParameters::Converter
      include Yoomoney::Internal::Type::RequestParameters

      attr_accessor deal_id: String

      def initialize: (
        deal_id: String,
        ?request_options: Yoomoney::request_opts
      ) -> void

      def to_hash: -> {
        deal_id: String,
        request_options: Yoomoney::RequestOptions
      }
    end
  end
end
