module Yoomoney
  module Models
    type delivery_method = { type: String }

    class DeliveryMethod < Yoomoney::Internal::Type::BaseModel
      attr_accessor type: String

      def initialize: (type: String) -> void

      def to_hash: -> { type: String }
    end
  end
end
