module Yoomoney
  module Models
    type delivery_method_data =
      { type: Yoomoney::Models::DeliveryMethodData::type_ }

    class DeliveryMethodData < Yoomoney::Internal::Type::BaseModel
      attr_accessor type: Yoomoney::Models::DeliveryMethodData::type_

      def initialize: (
        type: Yoomoney::Models::DeliveryMethodData::type_
      ) -> void

      def to_hash: -> { type: Yoomoney::Models::DeliveryMethodData::type_ }

      type type_ = :self | :sms | :email

      module Type
        extend Yoomoney::Internal::Type::Enum

        SELF: :self
        SMS: :sms
        EMAIL: :email

        def self?.values: -> ::Array[Yoomoney::Models::DeliveryMethodData::type_]
      end
    end
  end
end
