module Yoomoney
  module Models
    type invoice =
      {
        id: String,
        cart: ::Array[Yoomoney::LineItem],
        created_at: Time,
        status: Yoomoney::Models::Invoice::status,
        cancellation_details: Yoomoney::Invoice::CancellationDetails,
        delivery_method: Yoomoney::Models::Invoice::delivery_method,
        description: String,
        expires_at: Time,
        metadata: ::Hash[Symbol, String],
        payment_details: Yoomoney::Invoice::PaymentDetails
      }

    class Invoice < Yoomoney::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor cart: ::Array[Yoomoney::LineItem]

      attr_accessor created_at: Time

      attr_accessor status: Yoomoney::Models::Invoice::status

      attr_reader cancellation_details: Yoomoney::Invoice::CancellationDetails?

      def cancellation_details=: (
        Yoomoney::Invoice::CancellationDetails
      ) -> Yoomoney::Invoice::CancellationDetails

      attr_reader delivery_method: Yoomoney::Models::Invoice::delivery_method?

      def delivery_method=: (
        Yoomoney::Models::Invoice::delivery_method
      ) -> Yoomoney::Models::Invoice::delivery_method

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader expires_at: Time?

      def expires_at=: (Time) -> Time

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader payment_details: Yoomoney::Invoice::PaymentDetails?

      def payment_details=: (
        Yoomoney::Invoice::PaymentDetails
      ) -> Yoomoney::Invoice::PaymentDetails

      def initialize: (
        id: String,
        cart: ::Array[Yoomoney::LineItem],
        created_at: Time,
        status: Yoomoney::Models::Invoice::status,
        ?cancellation_details: Yoomoney::Invoice::CancellationDetails,
        ?delivery_method: Yoomoney::Models::Invoice::delivery_method,
        ?description: String,
        ?expires_at: Time,
        ?metadata: ::Hash[Symbol, String],
        ?payment_details: Yoomoney::Invoice::PaymentDetails
      ) -> void

      def to_hash: -> {
        id: String,
        cart: ::Array[Yoomoney::LineItem],
        created_at: Time,
        status: Yoomoney::Models::Invoice::status,
        cancellation_details: Yoomoney::Invoice::CancellationDetails,
        delivery_method: Yoomoney::Models::Invoice::delivery_method,
        description: String,
        expires_at: Time,
        metadata: ::Hash[Symbol, String],
        payment_details: Yoomoney::Invoice::PaymentDetails
      }

      type status = :pending | :succeeded | :canceled

      module Status
        extend Yoomoney::Internal::Type::Enum

        PENDING: :pending
        SUCCEEDED: :succeeded
        CANCELED: :canceled

        def self?.values: -> ::Array[Yoomoney::Models::Invoice::status]
      end

      type cancellation_details = { party: String, reason: String }

      class CancellationDetails < Yoomoney::Internal::Type::BaseModel
        attr_accessor party: String

        attr_accessor reason: String

        def initialize: (party: String, reason: String) -> void

        def to_hash: -> { party: String, reason: String }
      end

      type delivery_method =
        Yoomoney::Invoice::DeliveryMethod::DeliveryMethodSelf
        | Yoomoney::DeliveryMethod

      module DeliveryMethod
        extend Yoomoney::Internal::Type::Union

        type delivery_method_self = { url: String }

        class DeliveryMethodSelf < Yoomoney::Models::DeliveryMethod
          def url: -> String?

          def url=: (String _) -> String

          def initialize: (?url: String) -> void

          def to_hash: -> { url: String }
        end

        def self?.variants: -> ::Array[Yoomoney::Models::Invoice::delivery_method]
      end

      type payment_details = { id: String, status: String }

      class PaymentDetails < Yoomoney::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor status: String

        def initialize: (id: String, status: String) -> void

        def to_hash: -> { id: String, status: String }
      end
    end
  end
end
