module Yoomoney
  module Models
    type invoice_retrieve_params =
      { invoice_id: String } & Yoomoney::Internal::Type::request_parameters

    class InvoiceRetrieveParams < Yoomoney::Internal::Type::BaseModel
      extend Yoomoney::Internal::Type::RequestParameters::Converter
      include Yoomoney::Internal::Type::RequestParameters

      attr_accessor invoice_id: String

      def initialize: (
        invoice_id: String,
        ?request_options: Yoomoney::request_opts
      ) -> void

      def to_hash: -> {
        invoice_id: String,
        request_options: Yoomoney::RequestOptions
      }
    end
  end
end
