module Yoomoney
  module Models
    type invoice_create_params =
      {
        cart: ::Array[Yoomoney::LineItem],
        delivery_method: Yoomoney::Models::InvoiceCreateParams::delivery_method,
        idempotence_key: String,
        description: String,
        expires_at: Time,
        metadata: ::Hash[Symbol, String],
        payment_data: Yoomoney::InvoiceCreateParams::PaymentData
      }
      & Yoomoney::Internal::Type::request_parameters

    class InvoiceCreateParams < Yoomoney::Internal::Type::BaseModel
      extend Yoomoney::Internal::Type::RequestParameters::Converter
      include Yoomoney::Internal::Type::RequestParameters

      attr_accessor cart: ::Array[Yoomoney::LineItem]

      attr_accessor delivery_method: Yoomoney::Models::InvoiceCreateParams::delivery_method

      attr_accessor idempotence_key: String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader expires_at: Time?

      def expires_at=: (Time) -> Time

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader payment_data: Yoomoney::InvoiceCreateParams::PaymentData?

      def payment_data=: (
        Yoomoney::InvoiceCreateParams::PaymentData
      ) -> Yoomoney::InvoiceCreateParams::PaymentData

      def initialize: (
        cart: ::Array[Yoomoney::LineItem],
        delivery_method: Yoomoney::Models::InvoiceCreateParams::delivery_method,
        idempotence_key: String,
        ?description: String,
        ?expires_at: Time,
        ?metadata: ::Hash[Symbol, String],
        ?payment_data: Yoomoney::InvoiceCreateParams::PaymentData,
        ?request_options: Yoomoney::request_opts
      ) -> void

      def to_hash: -> {
        cart: ::Array[Yoomoney::LineItem],
        delivery_method: Yoomoney::Models::InvoiceCreateParams::delivery_method,
        idempotence_key: String,
        description: String,
        expires_at: Time,
        metadata: ::Hash[Symbol, String],
        payment_data: Yoomoney::InvoiceCreateParams::PaymentData,
        request_options: Yoomoney::RequestOptions
      }

      type delivery_method =
        Yoomoney::DeliveryMethodData
        | Yoomoney::InvoiceCreateParams::DeliveryMethod::DeliveryMethodDataSMS
        | Yoomoney::InvoiceCreateParams::DeliveryMethod::DeliveryMethodDataEmail

      module DeliveryMethod
        extend Yoomoney::Internal::Type::Union

        type delivery_method_data_sms = { phone: String }

        class DeliveryMethodDataSMS < Yoomoney::Models::DeliveryMethodData
          def phone: -> String

          def phone=: (String _) -> String

          def initialize: (phone: String) -> void

          def to_hash: -> { phone: String }
        end

        type delivery_method_data_email = { email: String }

        class DeliveryMethodDataEmail < Yoomoney::Models::DeliveryMethodData
          def email: -> String

          def email=: (String _) -> String

          def initialize: (email: String) -> void

          def to_hash: -> { email: String }
        end

        def self?.variants: -> ::Array[Yoomoney::Models::InvoiceCreateParams::delivery_method]
      end

      type payment_data =
        {
          amount: Yoomoney::MonetaryAmount,
          capture: bool,
          client_ip: String,
          description: String,
          metadata: ::Hash[Symbol, String],
          receipt: Yoomoney::ReceiptData,
          recipient: Yoomoney::Recipient,
          save_payment_method: bool
        }

      class PaymentData < Yoomoney::Internal::Type::BaseModel
        attr_accessor amount: Yoomoney::MonetaryAmount

        attr_reader capture: bool?

        def capture=: (bool) -> bool

        attr_reader client_ip: String?

        def client_ip=: (String) -> String

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader receipt: Yoomoney::ReceiptData?

        def receipt=: (Yoomoney::ReceiptData) -> Yoomoney::ReceiptData

        attr_reader recipient: Yoomoney::Recipient?

        def recipient=: (Yoomoney::Recipient) -> Yoomoney::Recipient

        attr_reader save_payment_method: bool?

        def save_payment_method=: (bool) -> bool

        def initialize: (
          amount: Yoomoney::MonetaryAmount,
          ?capture: bool,
          ?client_ip: String,
          ?description: String,
          ?metadata: ::Hash[Symbol, String],
          ?receipt: Yoomoney::ReceiptData,
          ?recipient: Yoomoney::Recipient,
          ?save_payment_method: bool
        ) -> void

        def to_hash: -> {
          amount: Yoomoney::MonetaryAmount,
          capture: bool,
          client_ip: String,
          description: String,
          metadata: ::Hash[Symbol, String],
          receipt: Yoomoney::ReceiptData,
          recipient: Yoomoney::Recipient,
          save_payment_method: bool
        }
      end
    end
  end
end
