module Yoomoney
  module Models
    type payment_cancel_params =
      { idempotence_key: String } & Yoomoney::Internal::Type::request_parameters

    class PaymentCancelParams < Yoomoney::Internal::Type::BaseModel
      extend Yoomoney::Internal::Type::RequestParameters::Converter
      include Yoomoney::Internal::Type::RequestParameters

      attr_accessor idempotence_key: String

      def initialize: (
        idempotence_key: String,
        ?request_options: Yoomoney::request_opts
      ) -> void

      def to_hash: -> {
        idempotence_key: String,
        request_options: Yoomoney::RequestOptions
      }
    end
  end
end
