module Yoomoney
  module Models
    type payment =
      {
        id: String,
        amount: Yoomoney::MonetaryAmount,
        created_at: Time,
        paid: bool,
        recipient: Yoomoney::Recipient,
        refundable: bool,
        status: Yoomoney::Models::payment_status,
        test_: bool,
        authorization_details: Yoomoney::Payment::AuthorizationDetails,
        cancellation_details: Yoomoney::Payment::CancellationDetails,
        captured_at: Time,
        confirmation: Yoomoney::Models::Payment::confirmation,
        deal: Yoomoney::PaymentDealInfo,
        description: String,
        expires_at: Time,
        income_amount: Yoomoney::MonetaryAmount,
        invoice_details: String,
        merchant_customer_id: String,
        metadata: ::Hash[Symbol, String],
        payment_method: Yoomoney::Models::Payment::payment_method,
        receipt_registration: Yoomoney::Models::receipt_registration_status,
        refunded_amount: Yoomoney::MonetaryAmount,
        transfers: ::Array[Yoomoney::Payment::Transfer]
      }

    class Payment < Yoomoney::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor amount: Yoomoney::MonetaryAmount

      attr_accessor created_at: Time

      attr_accessor paid: bool

      attr_accessor recipient: Yoomoney::Recipient

      attr_accessor refundable: bool

      attr_accessor status: Yoomoney::Models::payment_status

      attr_accessor test_: bool

      attr_reader authorization_details: Yoomoney::Payment::AuthorizationDetails?

      def authorization_details=: (
        Yoomoney::Payment::AuthorizationDetails
      ) -> Yoomoney::Payment::AuthorizationDetails

      attr_reader cancellation_details: Yoomoney::Payment::CancellationDetails?

      def cancellation_details=: (
        Yoomoney::Payment::CancellationDetails
      ) -> Yoomoney::Payment::CancellationDetails

      attr_reader captured_at: Time?

      def captured_at=: (Time) -> Time

      attr_reader confirmation: Yoomoney::Models::Payment::confirmation?

      def confirmation=: (
        Yoomoney::Models::Payment::confirmation
      ) -> Yoomoney::Models::Payment::confirmation

      attr_reader deal: Yoomoney::PaymentDealInfo?

      def deal=: (Yoomoney::PaymentDealInfo) -> Yoomoney::PaymentDealInfo

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader expires_at: Time?

      def expires_at=: (Time) -> Time

      attr_reader income_amount: Yoomoney::MonetaryAmount?

      def income_amount=: (Yoomoney::MonetaryAmount) -> Yoomoney::MonetaryAmount

      attr_reader invoice_details: String?

      def invoice_details=: (String) -> String

      attr_reader merchant_customer_id: String?

      def merchant_customer_id=: (String) -> String

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader payment_method: Yoomoney::Models::Payment::payment_method?

      def payment_method=: (
        Yoomoney::Models::Payment::payment_method
      ) -> Yoomoney::Models::Payment::payment_method

      attr_reader receipt_registration: Yoomoney::Models::receipt_registration_status?

      def receipt_registration=: (
        Yoomoney::Models::receipt_registration_status
      ) -> Yoomoney::Models::receipt_registration_status

      attr_reader refunded_amount: Yoomoney::MonetaryAmount?

      def refunded_amount=: (
        Yoomoney::MonetaryAmount
      ) -> Yoomoney::MonetaryAmount

      attr_reader transfers: ::Array[Yoomoney::Payment::Transfer]?

      def transfers=: (
        ::Array[Yoomoney::Payment::Transfer]
      ) -> ::Array[Yoomoney::Payment::Transfer]

      def initialize: (
        id: String,
        amount: Yoomoney::MonetaryAmount,
        created_at: Time,
        paid: bool,
        recipient: Yoomoney::Recipient,
        refundable: bool,
        status: Yoomoney::Models::payment_status,
        test_: bool,
        ?authorization_details: Yoomoney::Payment::AuthorizationDetails,
        ?cancellation_details: Yoomoney::Payment::CancellationDetails,
        ?captured_at: Time,
        ?confirmation: Yoomoney::Models::Payment::confirmation,
        ?deal: Yoomoney::PaymentDealInfo,
        ?description: String,
        ?expires_at: Time,
        ?income_amount: Yoomoney::MonetaryAmount,
        ?invoice_details: String,
        ?merchant_customer_id: String,
        ?metadata: ::Hash[Symbol, String],
        ?payment_method: Yoomoney::Models::Payment::payment_method,
        ?receipt_registration: Yoomoney::Models::receipt_registration_status,
        ?refunded_amount: Yoomoney::MonetaryAmount,
        ?transfers: ::Array[Yoomoney::Payment::Transfer]
      ) -> void

      def to_hash: -> {
        id: String,
        amount: Yoomoney::MonetaryAmount,
        created_at: Time,
        paid: bool,
        recipient: Yoomoney::Recipient,
        refundable: bool,
        status: Yoomoney::Models::payment_status,
        test_: bool,
        authorization_details: Yoomoney::Payment::AuthorizationDetails,
        cancellation_details: Yoomoney::Payment::CancellationDetails,
        captured_at: Time,
        confirmation: Yoomoney::Models::Payment::confirmation,
        deal: Yoomoney::PaymentDealInfo,
        description: String,
        expires_at: Time,
        income_amount: Yoomoney::MonetaryAmount,
        invoice_details: String,
        merchant_customer_id: String,
        metadata: ::Hash[Symbol, String],
        payment_method: Yoomoney::Models::Payment::payment_method,
        receipt_registration: Yoomoney::Models::receipt_registration_status,
        refunded_amount: Yoomoney::MonetaryAmount,
        transfers: ::Array[Yoomoney::Payment::Transfer]
      }

      type authorization_details =
        {
          three_d_secure: Yoomoney::Payment::AuthorizationDetails::ThreeDSecure,
          auth_code: String,
          rrn: String
        }

      class AuthorizationDetails < Yoomoney::Internal::Type::BaseModel
        attr_accessor three_d_secure: Yoomoney::Payment::AuthorizationDetails::ThreeDSecure

        attr_reader auth_code: String?

        def auth_code=: (String) -> String

        attr_reader rrn: String?

        def rrn=: (String) -> String

        def initialize: (
          three_d_secure: Yoomoney::Payment::AuthorizationDetails::ThreeDSecure,
          ?auth_code: String,
          ?rrn: String
        ) -> void

        def to_hash: -> {
          three_d_secure: Yoomoney::Payment::AuthorizationDetails::ThreeDSecure,
          auth_code: String,
          rrn: String
        }

        type three_d_secure = { applied: bool }

        class ThreeDSecure < Yoomoney::Internal::Type::BaseModel
          attr_accessor applied: bool

          def initialize: (applied: bool) -> void

          def to_hash: -> { applied: bool }
        end
      end

      type cancellation_details = { party: String, reason: String }

      class CancellationDetails < Yoomoney::Internal::Type::BaseModel
        attr_accessor party: String

        attr_accessor reason: String

        def initialize: (party: String, reason: String) -> void

        def to_hash: -> { party: String, reason: String }
      end

      type confirmation =
        Yoomoney::Payment::Confirmation::ConfirmationRedirect
        | Yoomoney::Confirmation
        | Yoomoney::Payment::Confirmation::ConfirmationQr
        | Yoomoney::Payment::Confirmation::ConfirmationEmbedded
        | Yoomoney::Payment::Confirmation::ConfirmationMobileApplication

      module Confirmation
        extend Yoomoney::Internal::Type::Union

        type confirmation_redirect =
          { confirmation_url: String, enforce: bool, return_url: String }

        class ConfirmationRedirect < Yoomoney::Models::Confirmation
          def confirmation_url: -> String

          def confirmation_url=: (String _) -> String

          def enforce: -> bool?

          def enforce=: (bool _) -> bool

          def return_url: -> String?

          def return_url=: (String _) -> String

          def initialize: (
            confirmation_url: String,
            ?enforce: bool,
            ?return_url: String
          ) -> void

          def to_hash: -> {
            confirmation_url: String,
            enforce: bool,
            return_url: String
          }
        end

        type confirmation_qr = { confirmation_url: String }

        class ConfirmationQr < Yoomoney::Models::Confirmation
          def confirmation_url: -> String?

          def confirmation_url=: (String _) -> String

          def initialize: (?confirmation_url: String) -> void

          def to_hash: -> { confirmation_url: String }
        end

        type confirmation_embedded = { confirmation_token: String }

        class ConfirmationEmbedded < Yoomoney::Models::Confirmation
          def confirmation_token: -> String?

          def confirmation_token=: (String _) -> String

          def initialize: (?confirmation_token: String) -> void

          def to_hash: -> { confirmation_token: String }
        end

        type confirmation_mobile_application = { confirmation_url: String }

        class ConfirmationMobileApplication < Yoomoney::Models::Confirmation
          def confirmation_url: -> String?

          def confirmation_url=: (String _) -> String

          def initialize: (?confirmation_url: String) -> void

          def to_hash: -> { confirmation_url: String }
        end

        def self?.variants: -> ::Array[Yoomoney::Models::Payment::confirmation]
      end

      type payment_method =
        Yoomoney::Payment::PaymentMethod::PaymentMethodBankCard
        | Yoomoney::PaymentMethod
        | Yoomoney::Payment::PaymentMethod::PaymentMethodAlfabank
        | Yoomoney::Payment::PaymentMethod::PaymentMethodSberbank
        | Yoomoney::Payment::PaymentMethod::PaymentMethodYooMoney
        | Yoomoney::Payment::PaymentMethod::PaymentMethodMobileBalance
        | Yoomoney::Payment::PaymentMethod::PaymentMethodB2bSberbank
        | Yoomoney::Payment::PaymentMethod::PaymentMethodSbp
        | Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate

      module PaymentMethod
        extend Yoomoney::Internal::Type::Union

        type payment_method_bank_card = { card: Yoomoney::BankCardData }

        class PaymentMethodBankCard < Yoomoney::Models::PaymentMethod
          def card: -> Yoomoney::BankCardData?

          def card=: (Yoomoney::BankCardData _) -> Yoomoney::BankCardData

          def initialize: (?card: Yoomoney::BankCardData) -> void

          def to_hash: -> { card: Yoomoney::BankCardData }
        end

        type payment_method_alfabank = { login: String }

        class PaymentMethodAlfabank < Yoomoney::Models::PaymentMethod
          def login: -> String?

          def login=: (String _) -> String

          def initialize: (?login: String) -> void

          def to_hash: -> { login: String }
        end

        type payment_method_sberbank = { phone: String }

        class PaymentMethodSberbank < Yoomoney::Models::PaymentMethod
          def phone: -> String?

          def phone=: (String _) -> String

          def initialize: (?phone: String) -> void

          def to_hash: -> { phone: String }
        end

        type payment_method_yoo_money = { account_number: String }

        class PaymentMethodYooMoney < Yoomoney::Models::PaymentMethod
          def account_number: -> String?

          def account_number=: (String _) -> String

          def initialize: (?account_number: String) -> void

          def to_hash: -> { account_number: String }
        end

        type payment_method_mobile_balance = { phone: String }

        class PaymentMethodMobileBalance < Yoomoney::Models::PaymentMethod
          def phone: -> String?

          def phone=: (String _) -> String

          def initialize: (?phone: String) -> void

          def to_hash: -> { phone: String }
        end

        type payment_method_b2b_sberbank =
          {
            payer_bank_details: Yoomoney::Payment::PaymentMethod::PaymentMethodB2bSberbank::PayerBankDetails,
            payment_purpose: String,
            vat_data: Yoomoney::B2bSberbankVatData
          }

        class PaymentMethodB2bSberbank < Yoomoney::Models::PaymentMethod
          def payer_bank_details: -> Yoomoney::Payment::PaymentMethod::PaymentMethodB2bSberbank::PayerBankDetails?

          def payer_bank_details=: (
            Yoomoney::Payment::PaymentMethod::PaymentMethodB2bSberbank::PayerBankDetails _
          ) -> Yoomoney::Payment::PaymentMethod::PaymentMethodB2bSberbank::PayerBankDetails

          def payment_purpose: -> String?

          def payment_purpose=: (String _) -> String

          def vat_data: -> Yoomoney::B2bSberbankVatData?

          def vat_data=: (
            Yoomoney::B2bSberbankVatData _
          ) -> Yoomoney::B2bSberbankVatData

          def initialize: (
            ?payer_bank_details: Yoomoney::Payment::PaymentMethod::PaymentMethodB2bSberbank::PayerBankDetails,
            ?payment_purpose: String,
            ?vat_data: Yoomoney::B2bSberbankVatData
          ) -> void

          def to_hash: -> {
            payer_bank_details: Yoomoney::Payment::PaymentMethod::PaymentMethodB2bSberbank::PayerBankDetails,
            payment_purpose: String,
            vat_data: Yoomoney::B2bSberbankVatData
          }

          type payer_bank_details =
            {
              account: String,
              address: String,
              bank_bik: String,
              bank_branch: String,
              bank_name: String,
              full_name: String,
              inn: String,
              short_name: String,
              kpp: String
            }

          class PayerBankDetails < Yoomoney::Internal::Type::BaseModel
            attr_accessor account: String

            attr_accessor address: String

            attr_accessor bank_bik: String

            attr_accessor bank_branch: String

            attr_accessor bank_name: String

            attr_accessor full_name: String

            attr_accessor inn: String

            attr_accessor short_name: String

            attr_reader kpp: String?

            def kpp=: (String) -> String

            def initialize: (
              account: String,
              address: String,
              bank_bik: String,
              bank_branch: String,
              bank_name: String,
              full_name: String,
              inn: String,
              short_name: String,
              ?kpp: String
            ) -> void

            def to_hash: -> {
              account: String,
              address: String,
              bank_bik: String,
              bank_branch: String,
              bank_name: String,
              full_name: String,
              inn: String,
              short_name: String,
              kpp: String
            }
          end
        end

        type payment_method_sbp =
          {
            payer_bank_details: Yoomoney::Payment::PaymentMethod::PaymentMethodSbp::PayerBankDetails,
            sbp_operation_id: String
          }

        class PaymentMethodSbp < Yoomoney::Models::PaymentMethod
          def payer_bank_details: -> Yoomoney::Payment::PaymentMethod::PaymentMethodSbp::PayerBankDetails?

          def payer_bank_details=: (
            Yoomoney::Payment::PaymentMethod::PaymentMethodSbp::PayerBankDetails _
          ) -> Yoomoney::Payment::PaymentMethod::PaymentMethodSbp::PayerBankDetails

          def sbp_operation_id: -> String?

          def sbp_operation_id=: (String _) -> String

          def initialize: (
            ?payer_bank_details: Yoomoney::Payment::PaymentMethod::PaymentMethodSbp::PayerBankDetails,
            ?sbp_operation_id: String
          ) -> void

          def to_hash: -> {
            payer_bank_details: Yoomoney::Payment::PaymentMethod::PaymentMethodSbp::PayerBankDetails,
            sbp_operation_id: String
          }

          type payer_bank_details = { bank_id: String, bic: String }

          class PayerBankDetails < Yoomoney::Internal::Type::BaseModel
            attr_accessor bank_id: String

            attr_accessor bic: String

            def initialize: (bank_id: String, bic: String) -> void

            def to_hash: -> { bank_id: String, bic: String }
          end
        end

        type payment_method_electronic_certificate =
          {
            articles: ::Array[Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::Article],
            electronic_certificate: Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::ElectronicCertificate
          }

        class PaymentMethodElectronicCertificate < Yoomoney::Models::PaymentMethod
          def articles: -> ::Array[Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::Article]?

          def articles=: (
            ::Array[Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::Article] _
          ) -> ::Array[Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::Article]

          def electronic_certificate: -> Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::ElectronicCertificate?

          def electronic_certificate=: (
            Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::ElectronicCertificate _
          ) -> Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::ElectronicCertificate

          def initialize: (
            ?articles: ::Array[Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::Article],
            ?electronic_certificate: Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::ElectronicCertificate
          ) -> void

          def to_hash: -> {
            articles: ::Array[Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::Article],
            electronic_certificate: Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::ElectronicCertificate
          }

          type article =
            {
              article_number: Integer,
              certificates: ::Array[Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::Article::Certificate],
              tru_code: String,
              article_code: String
            }

          class Article < Yoomoney::Internal::Type::BaseModel
            attr_accessor article_number: Integer

            attr_accessor certificates: ::Array[Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::Article::Certificate]

            attr_accessor tru_code: String

            attr_reader article_code: String?

            def article_code=: (String) -> String

            def initialize: (
              article_number: Integer,
              certificates: ::Array[Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::Article::Certificate],
              tru_code: String,
              ?article_code: String
            ) -> void

            def to_hash: -> {
              article_number: Integer,
              certificates: ::Array[Yoomoney::Payment::PaymentMethod::PaymentMethodElectronicCertificate::Article::Certificate],
              tru_code: String,
              article_code: String
            }

            type certificate =
              {
                applied_compensation: Yoomoney::MonetaryAmount,
                available_compensation: Yoomoney::MonetaryAmount,
                certificate_id: String,
                tru_quantity: Integer
              }

            class Certificate < Yoomoney::Internal::Type::BaseModel
              attr_accessor applied_compensation: Yoomoney::MonetaryAmount

              attr_accessor available_compensation: Yoomoney::MonetaryAmount

              attr_accessor certificate_id: String

              attr_accessor tru_quantity: Integer

              def initialize: (
                applied_compensation: Yoomoney::MonetaryAmount,
                available_compensation: Yoomoney::MonetaryAmount,
                certificate_id: String,
                tru_quantity: Integer
              ) -> void

              def to_hash: -> {
                applied_compensation: Yoomoney::MonetaryAmount,
                available_compensation: Yoomoney::MonetaryAmount,
                certificate_id: String,
                tru_quantity: Integer
              }
            end
          end

          type electronic_certificate =
            { amount: Yoomoney::MonetaryAmount, basket_id: String }

          class ElectronicCertificate < Yoomoney::Internal::Type::BaseModel
            attr_accessor amount: Yoomoney::MonetaryAmount

            attr_accessor basket_id: String

            def initialize: (
              amount: Yoomoney::MonetaryAmount,
              basket_id: String
            ) -> void

            def to_hash: -> {
              amount: Yoomoney::MonetaryAmount,
              basket_id: String
            }
          end
        end

        def self?.variants: -> ::Array[Yoomoney::Models::Payment::payment_method]
      end

      type transfer =
        {
          account_id: String,
          amount: Yoomoney::MonetaryAmount,
          status: Yoomoney::Models::Payment::Transfer::status,
          description: String,
          metadata: ::Hash[Symbol, String],
          platform_fee_amount: Yoomoney::MonetaryAmount
        }

      class Transfer < Yoomoney::Internal::Type::BaseModel
        attr_accessor account_id: String

        attr_accessor amount: Yoomoney::MonetaryAmount

        attr_accessor status: Yoomoney::Models::Payment::Transfer::status

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader platform_fee_amount: Yoomoney::MonetaryAmount?

        def platform_fee_amount=: (
          Yoomoney::MonetaryAmount
        ) -> Yoomoney::MonetaryAmount

        def initialize: (
          account_id: String,
          amount: Yoomoney::MonetaryAmount,
          status: Yoomoney::Models::Payment::Transfer::status,
          ?description: String,
          ?metadata: ::Hash[Symbol, String],
          ?platform_fee_amount: Yoomoney::MonetaryAmount
        ) -> void

        def to_hash: -> {
          account_id: String,
          amount: Yoomoney::MonetaryAmount,
          status: Yoomoney::Models::Payment::Transfer::status,
          description: String,
          metadata: ::Hash[Symbol, String],
          platform_fee_amount: Yoomoney::MonetaryAmount
        }

        type status = :pending | :waiting_for_capture | :succeeded | :canceled

        module Status
          extend Yoomoney::Internal::Type::Enum

          PENDING: :pending
          WAITING_FOR_CAPTURE: :waiting_for_capture
          SUCCEEDED: :succeeded
          CANCELED: :canceled

          def self?.values: -> ::Array[Yoomoney::Models::Payment::Transfer::status]
        end
      end
    end
  end
end
