module Yoomoney
  module Models
    type payment_method_create_params =
      {
        payment_method_data: Yoomoney::PaymentMethodCreateParams::PaymentMethodData,
        type: Yoomoney::Models::PaymentMethodCreateParams::type_,
        idempotence_key: String,
        payment_data: Yoomoney::PaymentMethodCreateParams::PaymentData,
        receipt: Yoomoney::ReceiptData
      }
      & Yoomoney::Internal::Type::request_parameters

    class PaymentMethodCreateParams < Yoomoney::Internal::Type::BaseModel
      extend Yoomoney::Internal::Type::RequestParameters::Converter
      include Yoomoney::Internal::Type::RequestParameters

      attr_accessor payment_method_data: Yoomoney::PaymentMethodCreateParams::PaymentMethodData

      attr_accessor type: Yoomoney::Models::PaymentMethodCreateParams::type_

      attr_accessor idempotence_key: String

      attr_reader payment_data: Yoomoney::PaymentMethodCreateParams::PaymentData?

      def payment_data=: (
        Yoomoney::PaymentMethodCreateParams::PaymentData
      ) -> Yoomoney::PaymentMethodCreateParams::PaymentData

      attr_reader receipt: Yoomoney::ReceiptData?

      def receipt=: (Yoomoney::ReceiptData) -> Yoomoney::ReceiptData

      def initialize: (
        payment_method_data: Yoomoney::PaymentMethodCreateParams::PaymentMethodData,
        type: Yoomoney::Models::PaymentMethodCreateParams::type_,
        idempotence_key: String,
        ?payment_data: Yoomoney::PaymentMethodCreateParams::PaymentData,
        ?receipt: Yoomoney::ReceiptData,
        ?request_options: Yoomoney::request_opts
      ) -> void

      def to_hash: -> {
        payment_method_data: Yoomoney::PaymentMethodCreateParams::PaymentMethodData,
        type: Yoomoney::Models::PaymentMethodCreateParams::type_,
        idempotence_key: String,
        payment_data: Yoomoney::PaymentMethodCreateParams::PaymentData,
        receipt: Yoomoney::ReceiptData,
        request_options: Yoomoney::RequestOptions
      }

      type payment_method_data =
        {
          type: Yoomoney::Models::PaymentMethodCreateParams::PaymentMethodData::type_,
          client_ip: String,
          confirmation: Yoomoney::PaymentMethodCreateParams::PaymentMethodData::Confirmation,
          holder: String
        }

      class PaymentMethodData < Yoomoney::Internal::Type::BaseModel
        attr_accessor type: Yoomoney::Models::PaymentMethodCreateParams::PaymentMethodData::type_

        attr_reader client_ip: String?

        def client_ip=: (String) -> String

        attr_reader confirmation: Yoomoney::PaymentMethodCreateParams::PaymentMethodData::Confirmation?

        def confirmation=: (
          Yoomoney::PaymentMethodCreateParams::PaymentMethodData::Confirmation
        ) -> Yoomoney::PaymentMethodCreateParams::PaymentMethodData::Confirmation

        attr_reader holder: String?

        def holder=: (String) -> String

        def initialize: (
          type: Yoomoney::Models::PaymentMethodCreateParams::PaymentMethodData::type_,
          ?client_ip: String,
          ?confirmation: Yoomoney::PaymentMethodCreateParams::PaymentMethodData::Confirmation,
          ?holder: String
        ) -> void

        def to_hash: -> {
          type: Yoomoney::Models::PaymentMethodCreateParams::PaymentMethodData::type_,
          client_ip: String,
          confirmation: Yoomoney::PaymentMethodCreateParams::PaymentMethodData::Confirmation,
          holder: String
        }

        type type_ = :bank_card

        module Type
          extend Yoomoney::Internal::Type::Enum

          BANK_CARD: :bank_card

          def self?.values: -> ::Array[Yoomoney::Models::PaymentMethodCreateParams::PaymentMethodData::type_]
        end

        type confirmation =
          {
            return_url: String,
            type: Yoomoney::Models::payment_methods_confirmation_type
          }

        class Confirmation < Yoomoney::Internal::Type::BaseModel
          attr_accessor return_url: String

          attr_accessor type: Yoomoney::Models::payment_methods_confirmation_type

          def initialize: (
            return_url: String,
            type: Yoomoney::Models::payment_methods_confirmation_type
          ) -> void

          def to_hash: -> {
            return_url: String,
            type: Yoomoney::Models::payment_methods_confirmation_type
          }
        end
      end

      type type_ = :bank_card

      module Type
        extend Yoomoney::Internal::Type::Enum

        BANK_CARD: :bank_card

        def self?.values: -> ::Array[Yoomoney::Models::PaymentMethodCreateParams::type_]
      end

      type payment_data =
        {
          amount: Yoomoney::MonetaryAmount,
          capture: bool,
          client_ip: String,
          description: String,
          metadata: ::Hash[Symbol, String],
          receipt: Yoomoney::ReceiptData,
          recipient: Yoomoney::Recipient,
          save_payment_method: bool
        }

      class PaymentData < Yoomoney::Internal::Type::BaseModel
        attr_accessor amount: Yoomoney::MonetaryAmount

        attr_reader capture: bool?

        def capture=: (bool) -> bool

        attr_reader client_ip: String?

        def client_ip=: (String) -> String

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader receipt: Yoomoney::ReceiptData?

        def receipt=: (Yoomoney::ReceiptData) -> Yoomoney::ReceiptData

        attr_reader recipient: Yoomoney::Recipient?

        def recipient=: (Yoomoney::Recipient) -> Yoomoney::Recipient

        attr_reader save_payment_method: bool?

        def save_payment_method=: (bool) -> bool

        def initialize: (
          amount: Yoomoney::MonetaryAmount,
          ?capture: bool,
          ?client_ip: String,
          ?description: String,
          ?metadata: ::Hash[Symbol, String],
          ?receipt: Yoomoney::ReceiptData,
          ?recipient: Yoomoney::Recipient,
          ?save_payment_method: bool
        ) -> void

        def to_hash: -> {
          amount: Yoomoney::MonetaryAmount,
          capture: bool,
          client_ip: String,
          description: String,
          metadata: ::Hash[Symbol, String],
          receipt: Yoomoney::ReceiptData,
          recipient: Yoomoney::Recipient,
          save_payment_method: bool
        }
      end
    end
  end
end
