module Yoomoney
  module Models
    type payment_method_data = { type: Yoomoney::Models::payment_method_type }

    class PaymentMethodData < Yoomoney::Internal::Type::BaseModel
      attr_accessor type: Yoomoney::Models::payment_method_type

      def initialize: (type: Yoomoney::Models::payment_method_type) -> void

      def to_hash: -> { type: Yoomoney::Models::payment_method_type }
    end
  end
end
