module Yoomoney
  module Models
    type payouts_list =
      { items: ::Array[Yoomoney::Payout], type: String, next_cursor: String }

    class PayoutsList < Yoomoney::Internal::Type::BaseModel
      attr_accessor items: ::Array[Yoomoney::Payout]

      attr_accessor type: String

      attr_reader next_cursor: String?

      def next_cursor=: (String) -> String

      def initialize: (
        items: ::Array[Yoomoney::Payout],
        type: String,
        ?next_cursor: String
      ) -> void

      def to_hash: -> {
        items: ::Array[Yoomoney::Payout],
        type: String,
        next_cursor: String
      }
    end
  end
end
