module Yoomoney
  module Models
    type personal_data_api =
      {
        id: String,
        created_at: Time,
        status: String,
        type: Yoomoney::Models::personal_data_type,
        cancellation_details: Yoomoney::PersonalDataAPI::CancellationDetails,
        expires_at: Time,
        metadata: ::Hash[Symbol, String]
      }

    class PersonalDataAPI < Yoomoney::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor status: String

      attr_accessor type: Yoomoney::Models::personal_data_type

      attr_reader cancellation_details: Yoomoney::PersonalDataAPI::CancellationDetails?

      def cancellation_details=: (
        Yoomoney::PersonalDataAPI::CancellationDetails
      ) -> Yoomoney::PersonalDataAPI::CancellationDetails

      attr_reader expires_at: Time?

      def expires_at=: (Time) -> Time

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      def initialize: (
        id: String,
        created_at: Time,
        status: String,
        type: Yoomoney::Models::personal_data_type,
        ?cancellation_details: Yoomoney::PersonalDataAPI::CancellationDetails,
        ?expires_at: Time,
        ?metadata: ::Hash[Symbol, String]
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        status: String,
        type: Yoomoney::Models::personal_data_type,
        cancellation_details: Yoomoney::PersonalDataAPI::CancellationDetails,
        expires_at: Time,
        metadata: ::Hash[Symbol, String]
      }

      type cancellation_details = { party: String, reason: String }

      class CancellationDetails < Yoomoney::Internal::Type::BaseModel
        attr_accessor party: String

        attr_accessor reason: String

        def initialize: (party: String, reason: String) -> void

        def to_hash: -> { party: String, reason: String }
      end
    end
  end
end
