module Yoomoney
  module Models
    type personal_data_create_params =
      {
        first_name: String,
        last_name: String,
        type: Yoomoney::Models::personal_data_type,
        idempotence_key: String,
        metadata: ::Hash[Symbol, String],
        middle_name: String
      }
      & Yoomoney::Internal::Type::request_parameters

    class PersonalDataCreateParams < Yoomoney::Internal::Type::BaseModel
      extend Yoomoney::Internal::Type::RequestParameters::Converter
      include Yoomoney::Internal::Type::RequestParameters

      attr_accessor first_name: String

      attr_accessor last_name: String

      attr_accessor type: Yoomoney::Models::personal_data_type

      attr_accessor idempotence_key: String

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader middle_name: String?

      def middle_name=: (String) -> String

      def initialize: (
        first_name: String,
        last_name: String,
        type: Yoomoney::Models::personal_data_type,
        idempotence_key: String,
        ?metadata: ::Hash[Symbol, String],
        ?middle_name: String,
        ?request_options: Yoomoney::request_opts
      ) -> void

      def to_hash: -> {
        first_name: String,
        last_name: String,
        type: Yoomoney::Models::personal_data_type,
        idempotence_key: String,
        metadata: ::Hash[Symbol, String],
        middle_name: String,
        request_options: Yoomoney::RequestOptions
      }
    end
  end
end
