module Yoomoney
  module Models
    type personal_data_retrieve_params =
      {  } & Yoomoney::Internal::Type::request_parameters

    class PersonalDataRetrieveParams < Yoomoney::Internal::Type::BaseModel
      extend Yoomoney::Internal::Type::RequestParameters::Converter
      include Yoomoney::Internal::Type::RequestParameters

      def initialize: (?request_options: Yoomoney::request_opts) -> void

      def to_hash: -> { request_options: Yoomoney::RequestOptions }
    end
  end
end
