module Yoomoney
  module Models
    type receipt_data =
      {
        items: ::Array[Yoomoney::ReceiptData::Item],
        customer: Yoomoney::ReceiptDataCustomer,
        internet: bool,
        receipt_industry_details: ::Array[Yoomoney::IndustryDetails],
        receipt_operational_details: Yoomoney::OperationalDetails,
        tax_system_code: Integer,
        timezone: String
      }

    class ReceiptData < Yoomoney::Internal::Type::BaseModel
      attr_accessor items: ::Array[Yoomoney::ReceiptData::Item]

      attr_reader customer: Yoomoney::ReceiptDataCustomer?

      def customer=: (
        Yoomoney::ReceiptDataCustomer
      ) -> Yoomoney::ReceiptDataCustomer

      attr_reader internet: bool?

      def internet=: (bool) -> bool

      attr_reader receipt_industry_details: ::Array[Yoomoney::IndustryDetails]?

      def receipt_industry_details=: (
        ::Array[Yoomoney::IndustryDetails]
      ) -> ::Array[Yoomoney::IndustryDetails]

      attr_reader receipt_operational_details: Yoomoney::OperationalDetails?

      def receipt_operational_details=: (
        Yoomoney::OperationalDetails
      ) -> Yoomoney::OperationalDetails

      attr_reader tax_system_code: Integer?

      def tax_system_code=: (Integer) -> Integer

      attr_reader timezone: String?

      def timezone=: (String) -> String

      def initialize: (
        items: ::Array[Yoomoney::ReceiptData::Item],
        ?customer: Yoomoney::ReceiptDataCustomer,
        ?internet: bool,
        ?receipt_industry_details: ::Array[Yoomoney::IndustryDetails],
        ?receipt_operational_details: Yoomoney::OperationalDetails,
        ?tax_system_code: Integer,
        ?timezone: String
      ) -> void

      def to_hash: -> {
        items: ::Array[Yoomoney::ReceiptData::Item],
        customer: Yoomoney::ReceiptDataCustomer,
        internet: bool,
        receipt_industry_details: ::Array[Yoomoney::IndustryDetails],
        receipt_operational_details: Yoomoney::OperationalDetails,
        tax_system_code: Integer,
        timezone: String
      }

      type item =
        {
          amount: Yoomoney::MonetaryAmount,
          description: String,
          quantity: Float,
          vat_code: Integer,
          country_of_origin_code: String,
          customs_declaration_number: String,
          excise: String,
          mark_code_info: Yoomoney::MarkCodeInfo,
          mark_mode: String,
          mark_quantity: Yoomoney::MarkQuantity,
          measure: Yoomoney::Models::receipt_item_measure,
          payment_mode: Yoomoney::Models::receipt_item_payment_mode,
          payment_subject: Yoomoney::Models::receipt_item_payment_subject,
          payment_subject_industry_details: ::Array[Yoomoney::IndustryDetails],
          planned_status: Integer,
          product_code: String
        }

      class Item < Yoomoney::Internal::Type::BaseModel
        attr_accessor amount: Yoomoney::MonetaryAmount

        attr_accessor description: String

        attr_accessor quantity: Float

        attr_accessor vat_code: Integer

        attr_reader country_of_origin_code: String?

        def country_of_origin_code=: (String) -> String

        attr_reader customs_declaration_number: String?

        def customs_declaration_number=: (String) -> String

        attr_reader excise: String?

        def excise=: (String) -> String

        attr_reader mark_code_info: Yoomoney::MarkCodeInfo?

        def mark_code_info=: (Yoomoney::MarkCodeInfo) -> Yoomoney::MarkCodeInfo

        attr_reader mark_mode: String?

        def mark_mode=: (String) -> String

        attr_reader mark_quantity: Yoomoney::MarkQuantity?

        def mark_quantity=: (Yoomoney::MarkQuantity) -> Yoomoney::MarkQuantity

        attr_reader measure: Yoomoney::Models::receipt_item_measure?

        def measure=: (
          Yoomoney::Models::receipt_item_measure
        ) -> Yoomoney::Models::receipt_item_measure

        attr_reader payment_mode: Yoomoney::Models::receipt_item_payment_mode?

        def payment_mode=: (
          Yoomoney::Models::receipt_item_payment_mode
        ) -> Yoomoney::Models::receipt_item_payment_mode

        attr_reader payment_subject: Yoomoney::Models::receipt_item_payment_subject?

        def payment_subject=: (
          Yoomoney::Models::receipt_item_payment_subject
        ) -> Yoomoney::Models::receipt_item_payment_subject

        attr_reader payment_subject_industry_details: ::Array[Yoomoney::IndustryDetails]?

        def payment_subject_industry_details=: (
          ::Array[Yoomoney::IndustryDetails]
        ) -> ::Array[Yoomoney::IndustryDetails]

        attr_reader planned_status: Integer?

        def planned_status=: (Integer) -> Integer

        attr_reader product_code: String?

        def product_code=: (String) -> String

        def initialize: (
          amount: Yoomoney::MonetaryAmount,
          description: String,
          quantity: Float,
          vat_code: Integer,
          ?country_of_origin_code: String,
          ?customs_declaration_number: String,
          ?excise: String,
          ?mark_code_info: Yoomoney::MarkCodeInfo,
          ?mark_mode: String,
          ?mark_quantity: Yoomoney::MarkQuantity,
          ?measure: Yoomoney::Models::receipt_item_measure,
          ?payment_mode: Yoomoney::Models::receipt_item_payment_mode,
          ?payment_subject: Yoomoney::Models::receipt_item_payment_subject,
          ?payment_subject_industry_details: ::Array[Yoomoney::IndustryDetails],
          ?planned_status: Integer,
          ?product_code: String
        ) -> void

        def to_hash: -> {
          amount: Yoomoney::MonetaryAmount,
          description: String,
          quantity: Float,
          vat_code: Integer,
          country_of_origin_code: String,
          customs_declaration_number: String,
          excise: String,
          mark_code_info: Yoomoney::MarkCodeInfo,
          mark_mode: String,
          mark_quantity: Yoomoney::MarkQuantity,
          measure: Yoomoney::Models::receipt_item_measure,
          payment_mode: Yoomoney::Models::receipt_item_payment_mode,
          payment_subject: Yoomoney::Models::receipt_item_payment_subject,
          payment_subject_industry_details: ::Array[Yoomoney::IndustryDetails],
          planned_status: Integer,
          product_code: String
        }
      end
    end
  end
end
