module Yoomoney
  module Models
    type receipt_item_supplier = { name: String, phone: String }

    class ReceiptItemSupplier < Yoomoney::Internal::Type::BaseModel
      attr_reader name: String?

      def name=: (String) -> String

      attr_reader phone: String?

      def phone=: (String) -> String

      def initialize: (?name: String, ?phone: String) -> void

      def to_hash: -> { name: String, phone: String }
    end
  end
end
