module Yoomoney
  module Models
    type receipt_list_response =
      { items: ::Array[Yoomoney::Receipt], type: String, next_cursor: String }

    class ReceiptListResponse < Yoomoney::Internal::Type::BaseModel
      attr_accessor items: ::Array[Yoomoney::Receipt]

      attr_accessor type: String

      attr_reader next_cursor: String?

      def next_cursor=: (String) -> String

      def initialize: (
        items: ::Array[Yoomoney::Receipt],
        type: String,
        ?next_cursor: String
      ) -> void

      def to_hash: -> {
        items: ::Array[Yoomoney::Receipt],
        type: String,
        next_cursor: String
      }
    end
  end
end
