module Yoomoney
  module Models
    type receipt_data =
      {
        items: ::Array[Yoomoney::ReceiptDataItem],
        customer: Yoomoney::ReceiptDataCustomer,
        internet: bool,
        receipt_industry_details: ::Array[Yoomoney::IndustryDetails],
        receipt_operational_details: Yoomoney::OperationalDetails,
        tax_system_code: Integer,
        timezone: String
      }

    class ReceiptData < Yoomoney::Internal::Type::BaseModel
      attr_accessor items: ::Array[Yoomoney::ReceiptDataItem]

      attr_reader customer: Yoomoney::ReceiptDataCustomer?

      def customer=: (
        Yoomoney::ReceiptDataCustomer
      ) -> Yoomoney::ReceiptDataCustomer

      attr_reader internet: bool?

      def internet=: (bool) -> bool

      attr_reader receipt_industry_details: ::Array[Yoomoney::IndustryDetails]?

      def receipt_industry_details=: (
        ::Array[Yoomoney::IndustryDetails]
      ) -> ::Array[Yoomoney::IndustryDetails]

      attr_reader receipt_operational_details: Yoomoney::OperationalDetails?

      def receipt_operational_details=: (
        Yoomoney::OperationalDetails
      ) -> Yoomoney::OperationalDetails

      attr_reader tax_system_code: Integer?

      def tax_system_code=: (Integer) -> Integer

      attr_reader timezone: String?

      def timezone=: (String) -> String

      def initialize: (
        items: ::Array[Yoomoney::ReceiptDataItem],
        ?customer: Yoomoney::ReceiptDataCustomer,
        ?internet: bool,
        ?receipt_industry_details: ::Array[Yoomoney::IndustryDetails],
        ?receipt_operational_details: Yoomoney::OperationalDetails,
        ?tax_system_code: Integer,
        ?timezone: String
      ) -> void

      def to_hash: -> {
        items: ::Array[Yoomoney::ReceiptDataItem],
        customer: Yoomoney::ReceiptDataCustomer,
        internet: bool,
        receipt_industry_details: ::Array[Yoomoney::IndustryDetails],
        receipt_operational_details: Yoomoney::OperationalDetails,
        tax_system_code: Integer,
        timezone: String
      }
    end
  end
end
