module Yoomoney
  module Models
    type receipt_create_params =
      {
        customer: Yoomoney::ReceiptDataCustomer,
        items: ::Array[Yoomoney::ReceiptCreateParams::Item],
        send_: bool,
        settlements: ::Array[Yoomoney::Settlement],
        type: Yoomoney::Models::receipt_type,
        idempotence_key: String,
        additional_user_props: Yoomoney::ReceiptCreateParams::AdditionalUserProps,
        internet: bool,
        on_behalf_of: String,
        payment_id: String,
        receipt_industry_details: ::Array[Yoomoney::IndustryDetails],
        receipt_operational_details: Yoomoney::OperationalDetails,
        refund_id: String,
        tax_system_code: Integer,
        timezone: String
      }
      & Yoomoney::Internal::Type::request_parameters

    class ReceiptCreateParams < Yoomoney::Internal::Type::BaseModel
      extend Yoomoney::Internal::Type::RequestParameters::Converter
      include Yoomoney::Internal::Type::RequestParameters

      attr_accessor customer: Yoomoney::ReceiptDataCustomer

      attr_accessor items: ::Array[Yoomoney::ReceiptCreateParams::Item]

      attr_accessor send_: bool

      attr_accessor settlements: ::Array[Yoomoney::Settlement]

      attr_accessor type: Yoomoney::Models::receipt_type

      attr_accessor idempotence_key: String

      attr_reader additional_user_props: Yoomoney::ReceiptCreateParams::AdditionalUserProps?

      def additional_user_props=: (
        Yoomoney::ReceiptCreateParams::AdditionalUserProps
      ) -> Yoomoney::ReceiptCreateParams::AdditionalUserProps

      attr_reader internet: bool?

      def internet=: (bool) -> bool

      attr_reader on_behalf_of: String?

      def on_behalf_of=: (String) -> String

      attr_reader payment_id: String?

      def payment_id=: (String) -> String

      attr_reader receipt_industry_details: ::Array[Yoomoney::IndustryDetails]?

      def receipt_industry_details=: (
        ::Array[Yoomoney::IndustryDetails]
      ) -> ::Array[Yoomoney::IndustryDetails]

      attr_reader receipt_operational_details: Yoomoney::OperationalDetails?

      def receipt_operational_details=: (
        Yoomoney::OperationalDetails
      ) -> Yoomoney::OperationalDetails

      attr_reader refund_id: String?

      def refund_id=: (String) -> String

      attr_reader tax_system_code: Integer?

      def tax_system_code=: (Integer) -> Integer

      attr_reader timezone: String?

      def timezone=: (String) -> String

      def initialize: (
        customer: Yoomoney::ReceiptDataCustomer,
        items: ::Array[Yoomoney::ReceiptCreateParams::Item],
        send_: bool,
        settlements: ::Array[Yoomoney::Settlement],
        type: Yoomoney::Models::receipt_type,
        idempotence_key: String,
        ?additional_user_props: Yoomoney::ReceiptCreateParams::AdditionalUserProps,
        ?internet: bool,
        ?on_behalf_of: String,
        ?payment_id: String,
        ?receipt_industry_details: ::Array[Yoomoney::IndustryDetails],
        ?receipt_operational_details: Yoomoney::OperationalDetails,
        ?refund_id: String,
        ?tax_system_code: Integer,
        ?timezone: String,
        ?request_options: Yoomoney::request_opts
      ) -> void

      def to_hash: -> {
        customer: Yoomoney::ReceiptDataCustomer,
        items: ::Array[Yoomoney::ReceiptCreateParams::Item],
        send_: bool,
        settlements: ::Array[Yoomoney::Settlement],
        type: Yoomoney::Models::receipt_type,
        idempotence_key: String,
        additional_user_props: Yoomoney::ReceiptCreateParams::AdditionalUserProps,
        internet: bool,
        on_behalf_of: String,
        payment_id: String,
        receipt_industry_details: ::Array[Yoomoney::IndustryDetails],
        receipt_operational_details: Yoomoney::OperationalDetails,
        refund_id: String,
        tax_system_code: Integer,
        timezone: String,
        request_options: Yoomoney::RequestOptions
      }

      type item =
        {
          additional_payment_subject_props: String,
          agent_type: Yoomoney::Models::receipt_item_agent_type,
          supplier: Yoomoney::ReceiptCreateParams::Item::Supplier
        }

      class Item < Yoomoney::Models::ReceiptDataItem
        def additional_payment_subject_props: -> String?

        def additional_payment_subject_props=: (String _) -> String

        def agent_type: -> Yoomoney::Models::receipt_item_agent_type?

        def agent_type=: (
          Yoomoney::Models::receipt_item_agent_type _
        ) -> Yoomoney::Models::receipt_item_agent_type

        def supplier: -> Yoomoney::ReceiptCreateParams::Item::Supplier?

        def supplier=: (
          Yoomoney::ReceiptCreateParams::Item::Supplier _
        ) -> Yoomoney::ReceiptCreateParams::Item::Supplier

        def initialize: (
          ?additional_payment_subject_props: String,
          ?agent_type: Yoomoney::Models::receipt_item_agent_type,
          ?supplier: Yoomoney::ReceiptCreateParams::Item::Supplier
        ) -> void

        def to_hash: -> {
          additional_payment_subject_props: String,
          agent_type: Yoomoney::Models::receipt_item_agent_type,
          supplier: Yoomoney::ReceiptCreateParams::Item::Supplier
        }

        type supplier = { inn: String }

        class Supplier < Yoomoney::Models::ReceiptItemSupplier
          def inn: -> String?

          def inn=: (String _) -> String

          def initialize: (?inn: String) -> void

          def to_hash: -> { inn: String }
        end
      end

      type additional_user_props = { name: String, value: String }

      class AdditionalUserProps < Yoomoney::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor value: String

        def initialize: (name: String, value: String) -> void

        def to_hash: -> { name: String, value: String }
      end
    end
  end
end
