module Yoomoney
  module Models
    type receipt_item_measure =
      :piece
      | :gram
      | :kilogram
      | :ton
      | :centimeter
      | :decimeter
      | :meter
      | :square_centimeter
      | :square_decimeter
      | :square_meter
      | :milliliter
      | :liter
      | :cubic_meter
      | :kilowatt_hour
      | :gigacalorie
      | :day
      | :hour
      | :minute
      | :second
      | :kilobyte
      | :megabyte
      | :gigabyte
      | :terabyte
      | :another

    module ReceiptItemMeasure
      extend Yoomoney::Internal::Type::Enum

      PIECE: :piece
      GRAM: :gram
      KILOGRAM: :kilogram
      TON: :ton
      CENTIMETER: :centimeter
      DECIMETER: :decimeter
      METER: :meter
      SQUARE_CENTIMETER: :square_centimeter
      SQUARE_DECIMETER: :square_decimeter
      SQUARE_METER: :square_meter
      MILLILITER: :milliliter
      LITER: :liter
      CUBIC_METER: :cubic_meter
      KILOWATT_HOUR: :kilowatt_hour
      GIGACALORIE: :gigacalorie
      DAY: :day
      HOUR: :hour
      MINUTE: :minute
      SECOND: :second
      KILOBYTE: :kilobyte
      MEGABYTE: :megabyte
      GIGABYTE: :gigabyte
      TERABYTE: :terabyte
      ANOTHER: :another

      def self?.values: -> ::Array[Yoomoney::Models::receipt_item_measure]
    end
  end
end
