module Yoomoney
  module Models
    type refund =
      {
        id: String,
        amount: Yoomoney::MonetaryAmount,
        created_at: Time,
        payment_id: String,
        status: Yoomoney::Models::refund_status,
        cancellation_details: Yoomoney::Refund::CancellationDetails,
        deal: Yoomoney::Refund::Deal,
        description: String,
        metadata: ::Hash[Symbol, String],
        receipt_registration: Yoomoney::Models::receipt_registration_status,
        refund_authorization_details: Yoomoney::Refund::RefundAuthorizationDetails,
        refund_method: Yoomoney::Models::Refund::refund_method,
        sources: ::Array[Yoomoney::RefundSourcesData]
      }

    class Refund < Yoomoney::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor amount: Yoomoney::MonetaryAmount

      attr_accessor created_at: Time

      attr_accessor payment_id: String

      attr_accessor status: Yoomoney::Models::refund_status

      attr_reader cancellation_details: Yoomoney::Refund::CancellationDetails?

      def cancellation_details=: (
        Yoomoney::Refund::CancellationDetails
      ) -> Yoomoney::Refund::CancellationDetails

      attr_reader deal: Yoomoney::Refund::Deal?

      def deal=: (Yoomoney::Refund::Deal) -> Yoomoney::Refund::Deal

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader receipt_registration: Yoomoney::Models::receipt_registration_status?

      def receipt_registration=: (
        Yoomoney::Models::receipt_registration_status
      ) -> Yoomoney::Models::receipt_registration_status

      attr_reader refund_authorization_details: Yoomoney::Refund::RefundAuthorizationDetails?

      def refund_authorization_details=: (
        Yoomoney::Refund::RefundAuthorizationDetails
      ) -> Yoomoney::Refund::RefundAuthorizationDetails

      attr_reader refund_method: Yoomoney::Models::Refund::refund_method?

      def refund_method=: (
        Yoomoney::Models::Refund::refund_method
      ) -> Yoomoney::Models::Refund::refund_method

      attr_reader sources: ::Array[Yoomoney::RefundSourcesData]?

      def sources=: (
        ::Array[Yoomoney::RefundSourcesData]
      ) -> ::Array[Yoomoney::RefundSourcesData]

      def initialize: (
        id: String,
        amount: Yoomoney::MonetaryAmount,
        created_at: Time,
        payment_id: String,
        status: Yoomoney::Models::refund_status,
        ?cancellation_details: Yoomoney::Refund::CancellationDetails,
        ?deal: Yoomoney::Refund::Deal,
        ?description: String,
        ?metadata: ::Hash[Symbol, String],
        ?receipt_registration: Yoomoney::Models::receipt_registration_status,
        ?refund_authorization_details: Yoomoney::Refund::RefundAuthorizationDetails,
        ?refund_method: Yoomoney::Models::Refund::refund_method,
        ?sources: ::Array[Yoomoney::RefundSourcesData]
      ) -> void

      def to_hash: -> {
        id: String,
        amount: Yoomoney::MonetaryAmount,
        created_at: Time,
        payment_id: String,
        status: Yoomoney::Models::refund_status,
        cancellation_details: Yoomoney::Refund::CancellationDetails,
        deal: Yoomoney::Refund::Deal,
        description: String,
        metadata: ::Hash[Symbol, String],
        receipt_registration: Yoomoney::Models::receipt_registration_status,
        refund_authorization_details: Yoomoney::Refund::RefundAuthorizationDetails,
        refund_method: Yoomoney::Models::Refund::refund_method,
        sources: ::Array[Yoomoney::RefundSourcesData]
      }

      type cancellation_details = { party: String, reason: String }

      class CancellationDetails < Yoomoney::Internal::Type::BaseModel
        attr_accessor party: String

        attr_accessor reason: String

        def initialize: (party: String, reason: String) -> void

        def to_hash: -> { party: String, reason: String }
      end

      type deal =
        {
          id: String,
          refund_settlements: ::Array[Yoomoney::SettlementRefundItem]
        }

      class Deal < Yoomoney::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor refund_settlements: ::Array[Yoomoney::SettlementRefundItem]

        def initialize: (
          id: String,
          refund_settlements: ::Array[Yoomoney::SettlementRefundItem]
        ) -> void

        def to_hash: -> {
          id: String,
          refund_settlements: ::Array[Yoomoney::SettlementRefundItem]
        }
      end

      type refund_authorization_details = { rrn: String }

      class RefundAuthorizationDetails < Yoomoney::Internal::Type::BaseModel
        attr_reader rrn: String?

        def rrn=: (String) -> String

        def initialize: (?rrn: String) -> void

        def to_hash: -> { rrn: String }
      end

      type refund_method =
        Yoomoney::Refund::RefundMethod::SbpRefundMethod
        | Yoomoney::Refund::RefundMethod::ElectronicCertificateRefundMethod

      module RefundMethod
        extend Yoomoney::Internal::Type::Union

        type sbp_refund_method = { sbp_operation_id: String }

        class SbpRefundMethod < Yoomoney::Models::RefundMethod
          def sbp_operation_id: -> String?

          def sbp_operation_id=: (String _) -> String

          def initialize: (?sbp_operation_id: String) -> void

          def to_hash: -> { sbp_operation_id: String }
        end

        type electronic_certificate_refund_method =
          {
            articles: ::Array[Yoomoney::ElectronicCertificateRefundArticle],
            electronic_certificate: Yoomoney::Refund::RefundMethod::ElectronicCertificateRefundMethod::ElectronicCertificate
          }

        class ElectronicCertificateRefundMethod < Yoomoney::Models::RefundMethod
          def articles: -> ::Array[Yoomoney::ElectronicCertificateRefundArticle]?

          def articles=: (
            ::Array[Yoomoney::ElectronicCertificateRefundArticle] _
          ) -> ::Array[Yoomoney::ElectronicCertificateRefundArticle]

          def electronic_certificate: -> Yoomoney::Refund::RefundMethod::ElectronicCertificateRefundMethod::ElectronicCertificate?

          def electronic_certificate=: (
            Yoomoney::Refund::RefundMethod::ElectronicCertificateRefundMethod::ElectronicCertificate _
          ) -> Yoomoney::Refund::RefundMethod::ElectronicCertificateRefundMethod::ElectronicCertificate

          def initialize: (
            ?articles: ::Array[Yoomoney::ElectronicCertificateRefundArticle],
            ?electronic_certificate: Yoomoney::Refund::RefundMethod::ElectronicCertificateRefundMethod::ElectronicCertificate
          ) -> void

          def to_hash: -> {
            articles: ::Array[Yoomoney::ElectronicCertificateRefundArticle],
            electronic_certificate: Yoomoney::Refund::RefundMethod::ElectronicCertificateRefundMethod::ElectronicCertificate
          }

          type electronic_certificate =
            { amount: Yoomoney::MonetaryAmount, basket_id: String }

          class ElectronicCertificate < Yoomoney::Internal::Type::BaseModel
            attr_accessor amount: Yoomoney::MonetaryAmount

            attr_accessor basket_id: String

            def initialize: (
              amount: Yoomoney::MonetaryAmount,
              basket_id: String
            ) -> void

            def to_hash: -> {
              amount: Yoomoney::MonetaryAmount,
              basket_id: String
            }
          end
        end

        def self?.variants: -> ::Array[Yoomoney::Models::Refund::refund_method]
      end
    end
  end
end
