module Yoomoney
  module Models
    type refund_retrieve_params =
      { refund_id: String } & Yoomoney::Internal::Type::request_parameters

    class RefundRetrieveParams < Yoomoney::Internal::Type::BaseModel
      extend Yoomoney::Internal::Type::RequestParameters::Converter
      include Yoomoney::Internal::Type::RequestParameters

      attr_accessor refund_id: String

      def initialize: (
        refund_id: String,
        ?request_options: Yoomoney::request_opts
      ) -> void

      def to_hash: -> {
        refund_id: String,
        request_options: Yoomoney::RequestOptions
      }
    end
  end
end
