module Yoomoney
  module Models
    type save_payment_method_bank_card =
      {
        id: String,
        holder: String,
        saved: bool,
        status: Yoomoney::Models::payment_method_status,
        type: Yoomoney::Models::SavePaymentMethodBankCard::type_,
        card: Yoomoney::BankCardData,
        confirmation: Yoomoney::SavePaymentMethodBankCard::Confirmation,
        title: String
      }

    class SavePaymentMethodBankCard < Yoomoney::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor holder: String

      attr_accessor saved: bool

      attr_accessor status: Yoomoney::Models::payment_method_status

      attr_accessor type: Yoomoney::Models::SavePaymentMethodBankCard::type_

      attr_reader card: Yoomoney::BankCardData?

      def card=: (Yoomoney::BankCardData) -> Yoomoney::BankCardData

      attr_reader confirmation: Yoomoney::SavePaymentMethodBankCard::Confirmation?

      def confirmation=: (
        Yoomoney::SavePaymentMethodBankCard::Confirmation
      ) -> Yoomoney::SavePaymentMethodBankCard::Confirmation

      attr_reader title: String?

      def title=: (String) -> String

      def initialize: (
        id: String,
        holder: String,
        saved: bool,
        status: Yoomoney::Models::payment_method_status,
        type: Yoomoney::Models::SavePaymentMethodBankCard::type_,
        ?card: Yoomoney::BankCardData,
        ?confirmation: Yoomoney::SavePaymentMethodBankCard::Confirmation,
        ?title: String
      ) -> void

      def to_hash: -> {
        id: String,
        holder: String,
        saved: bool,
        status: Yoomoney::Models::payment_method_status,
        type: Yoomoney::Models::SavePaymentMethodBankCard::type_,
        card: Yoomoney::BankCardData,
        confirmation: Yoomoney::SavePaymentMethodBankCard::Confirmation,
        title: String
      }

      type type_ = :bank_card

      module Type
        extend Yoomoney::Internal::Type::Enum

        BANK_CARD: :bank_card

        def self?.values: -> ::Array[Yoomoney::Models::SavePaymentMethodBankCard::type_]
      end

      type confirmation =
        {
          type: Yoomoney::Models::payment_methods_confirmation_type,
          confirmation_url: String
        }

      class Confirmation < Yoomoney::Internal::Type::BaseModel
        attr_accessor type: Yoomoney::Models::payment_methods_confirmation_type

        attr_reader confirmation_url: String?

        def confirmation_url=: (String) -> String

        def initialize: (
          type: Yoomoney::Models::payment_methods_confirmation_type,
          ?confirmation_url: String
        ) -> void

        def to_hash: -> {
          type: Yoomoney::Models::payment_methods_confirmation_type,
          confirmation_url: String
        }
      end
    end
  end
end
