module Yoomoney
  module Models
    type sbp_bank_list_response =
      {
        items: ::Array[Yoomoney::Models::SbpBankListResponse::Item],
        type: String
      }

    class SbpBankListResponse < Yoomoney::Internal::Type::BaseModel
      attr_accessor items: ::Array[Yoomoney::Models::SbpBankListResponse::Item]

      attr_accessor type: String

      def initialize: (
        items: ::Array[Yoomoney::Models::SbpBankListResponse::Item],
        type: String
      ) -> void

      def to_hash: -> {
        items: ::Array[Yoomoney::Models::SbpBankListResponse::Item],
        type: String
      }

      type item = { bank_id: String, bic: String, name: String }

      class Item < Yoomoney::Internal::Type::BaseModel
        attr_accessor bank_id: String

        attr_accessor bic: String

        attr_accessor name: String

        def initialize: (bank_id: String, bic: String, name: String) -> void

        def to_hash: -> { bank_id: String, bic: String, name: String }
      end
    end
  end
end
