module Yoomoney
  module Models
    type settlement =
      {
        amount: Yoomoney::MonetaryAmount,
        type: Yoomoney::Models::Settlement::type_
      }

    class Settlement < Yoomoney::Internal::Type::BaseModel
      attr_accessor amount: Yoomoney::MonetaryAmount

      attr_accessor type: Yoomoney::Models::Settlement::type_

      def initialize: (
        amount: Yoomoney::MonetaryAmount,
        type: Yoomoney::Models::Settlement::type_
      ) -> void

      def to_hash: -> {
        amount: Yoomoney::MonetaryAmount,
        type: Yoomoney::Models::Settlement::type_
      }

      type type_ = :cashless | :prepayment | :postpayment | :consideration

      module Type
        extend Yoomoney::Internal::Type::Enum

        CASHLESS: :cashless
        PREPAYMENT: :prepayment
        POSTPAYMENT: :postpayment
        CONSIDERATION: :consideration

        def self?.values: -> ::Array[Yoomoney::Models::Settlement::type_]
      end
    end
  end
end
