module Yoomoney
  module Models
    type settlement_refund_item =
      {
        amount: Yoomoney::MonetaryAmount,
        type: Yoomoney::Models::settlement_item_type
      }

    class SettlementRefundItem < Yoomoney::Internal::Type::BaseModel
      attr_accessor amount: Yoomoney::MonetaryAmount

      attr_accessor type: Yoomoney::Models::settlement_item_type

      def initialize: (
        amount: Yoomoney::MonetaryAmount,
        type: Yoomoney::Models::settlement_item_type
      ) -> void

      def to_hash: -> {
        amount: Yoomoney::MonetaryAmount,
        type: Yoomoney::Models::settlement_item_type
      }
    end
  end
end
