module Yoomoney
  module Models
    type settlement = { amount: Yoomoney::MonetaryAmount, type: String }

    class Settlement < Yoomoney::Internal::Type::BaseModel
      attr_accessor amount: Yoomoney::MonetaryAmount

      attr_accessor type: String

      def initialize: (amount: Yoomoney::MonetaryAmount, type: String) -> void

      def to_hash: -> { amount: Yoomoney::MonetaryAmount, type: String }
    end
  end
end
