module Yoomoney
  module Models
    type webhook_list_response =
      { items: ::Array[Yoomoney::Webhook], type: String }

    class WebhookListResponse < Yoomoney::Internal::Type::BaseModel
      attr_accessor items: ::Array[Yoomoney::Webhook]

      attr_accessor type: String

      def initialize: (items: ::Array[Yoomoney::Webhook], type: String) -> void

      def to_hash: -> { items: ::Array[Yoomoney::Webhook], type: String }
    end
  end
end
