configured_endpoints: 29
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hexlet%2Fyoomoney-76c48bfc29ec5934459d6c20e809224b34b87fda5d6c6ecd5a7efe59355fbca8.yml
openapi_spec_hash: 7e94b0c7cb4ea16aec0cbbbbcb4dffe9
config_hash: a77e09a0fcdf86f6a6b0bf45e2e254b0
