module Yoomoney
  module Resources
    class Invoices
      def create: (
        cart: ::Array[Yoomoney::LineItem],
        delivery_method: Yoomoney::Models::InvoiceCreateParams::delivery_method,
        idempotence_key: String,
        ?description: String,
        ?expires_at: Time,
        ?metadata: ::Hash[Symbol, String],
        ?payment_data: Yoomoney::InvoiceCreateParams::PaymentData,
        ?request_options: Yoomoney::request_opts
      ) -> Yoomoney::Invoice

      def retrieve: (
        String invoice_id,
        ?request_options: Yoomoney::request_opts
      ) -> Yoomoney::Invoice

      def initialize: (client: Yoomoney::Client) -> void
    end
  end
end
