module Yoomoney
  module Resources
    class PaymentMethods
      def create: (
        payment_method_data: Yoomoney::PaymentMethodCreateParams::PaymentMethodData,
        type: Yoomoney::Models::PaymentMethodCreateParams::type_,
        idempotence_key: String,
        ?payment_data: Yoomoney::PaymentMethodCreateParams::PaymentData,
        ?receipt: Yoomoney::ReceiptData,
        ?request_options: Yoomoney::request_opts
      ) -> Yoomoney::SavePaymentMethodBankCard

      def retrieve: (
        String payment_method_id,
        ?request_options: Yoomoney::request_opts
      ) -> Yoomoney::SavePaymentMethodBankCard

      def initialize: (client: Yoomoney::Client) -> void
    end
  end
end
