module Yoomoney
  module Resources
    class PersonalData
      def create: (
        first_name: String,
        last_name: String,
        type: Yoomoney::Models::personal_data_type,
        idempotence_key: String,
        ?metadata: ::Hash[Symbol, String],
        ?middle_name: String,
        ?request_options: Yoomoney::request_opts
      ) -> Yoomoney::PersonalDataAPI

      def retrieve: (
        String personal_data_id,
        ?request_options: Yoomoney::request_opts
      ) -> Yoomoney::PersonalDataAPI

      def initialize: (client: Yoomoney::Client) -> void
    end
  end
end
