module Yoomoney
  module Resources
    class PersonalData
      def create: (
        body: Yoomoney::Models::PersonalDataCreateParams::body,
        idempotence_key: String,
        ?request_options: Yoomoney::request_opts
      ) -> Yoomoney::PersonalDataAPI

      def retrieve: (
        String personal_data_id,
        ?request_options: Yoomoney::request_opts
      ) -> Yoomoney::PersonalDataAPI

      def initialize: (client: Yoomoney::Client) -> void
    end
  end
end
